version: '3.9'

services:
  db:
    image: postgres:15
    container_name: saas-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: saas_main
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - saas-net

volumes:
  db_data:

networks:
  saas-net:
    driver: bridge
